import { PrismaService } from '../../database/prisma/prisma.service';
import { NotificationsService } from '../notifications/notifications.service';
import { CreateTagReportDto } from './dto/create-tag-report.dto';
import { RedisService } from '../../database/redis/redis.service';
export declare class TagsService {
    private prisma;
    private notificationsService;
    private redisService;
    private readonly LOST_TAGS_KEY;
    constructor(prisma: PrismaService, notificationsService: NotificationsService, redisService: RedisService);
    getTagReportDetail(id: string, currentUserId?: string): Promise<{
        latitude: number | null;
        longitude: number | null;
        radius: number;
        isExactLocation: boolean;
        isOwner: boolean | "" | undefined;
        scanHistory: {
            isEstimated: boolean;
            id: string;
            tagId: string;
            userId: string | null;
            scannedBy: string | null;
            phoneNumber: string | null;
            latitude: number | null;
            longitude: number | null;
            radius: number | null;
            message: string | null;
            images: import("@prisma/client").Prisma.JsonValue | null;
            status: import("@prisma/client").$Enums.TagReportStatus;
            scannedAt: Date;
        }[];
        tag: {
            pet: ({
                images: {
                    id: string;
                    url: string;
                    petId: string;
                    createdAt: Date;
                }[];
                owner: {
                    id: string;
                    email: string;
                    password: string | null;
                    role: import("@prisma/client").$Enums.Role;
                    name: string | null;
                    phone: string | null;
                    gender: string | null;
                    dob: Date | null;
                    avatarUrl: string | null;
                    provider: string;
                    isDeleted: boolean;
                    createdAt: Date;
                    updatedAt: Date;
                    deletedAt: Date | null;
                    shelterId: string | null;
                    twoFactorSecret: string | null;
                    isTwoFactorEnabled: boolean;
                } | null;
            } & {
                id: string;
                name: string;
                species: string;
                breed: string | null;
                dob: Date | null;
                microchipNumber: string | null;
                description: string | null;
                status: import("@prisma/client").$Enums.PetStatus;
                gender: import("@prisma/client").$Enums.PetGender | null;
                size: import("@prisma/client").$Enums.PetSize | null;
                weight: number | null;
                color: string | null;
                lostPhotos: string | null;
                isVaccinated: boolean;
                isSpayedNeutered: boolean;
                contactName: string | null;
                contactPhone: string | null;
                contactAddress: string | null;
                traits: string | null;
                idealHome: string | null;
                personalityTags: import("@prisma/client").Prisma.JsonValue | null;
                goodWith: import("@prisma/client").Prisma.JsonValue | null;
                badWith: import("@prisma/client").Prisma.JsonValue | null;
                vaccinationRecordUrls: import("@prisma/client").Prisma.JsonValue | null;
                vetVerificationStatus: import("@prisma/client").$Enums.VerificationStatus;
                qrCodeUrl: string | null;
                qrVerificationStatus: import("@prisma/client").$Enums.VerificationStatus;
                ownerId: string | null;
                createdAt: Date;
                updatedAt: Date;
                shelterId: string | null;
                lostLatitude: number | null;
                lostLongitude: number | null;
                lostRadius: number | null;
                lostDate: Date | null;
                lostContactName: string | null;
                lostContactPhone: string | null;
                lostContactAddress: string | null;
                lostLocation: string | null;
                lostDateTime: string | null;
                lostDetails: string | null;
                needsQrReplacement: boolean;
            }) | null;
        } & {
            id: string;
            status: import("@prisma/client").$Enums.TagStatus;
            petId: string | null;
        };
        id: string;
        tagId: string;
        userId: string | null;
        scannedBy: string | null;
        phoneNumber: string | null;
        message: string | null;
        images: import("@prisma/client").Prisma.JsonValue | null;
        status: import("@prisma/client").$Enums.TagReportStatus;
        scannedAt: Date;
    }>;
    createTagReport(data: CreateTagReportDto, currentUserId?: string): Promise<{
        tag: {
            pet: ({
                owner: {
                    id: string;
                    email: string;
                    password: string | null;
                    role: import("@prisma/client").$Enums.Role;
                    name: string | null;
                    phone: string | null;
                    gender: string | null;
                    dob: Date | null;
                    avatarUrl: string | null;
                    provider: string;
                    isDeleted: boolean;
                    createdAt: Date;
                    updatedAt: Date;
                    deletedAt: Date | null;
                    shelterId: string | null;
                    twoFactorSecret: string | null;
                    isTwoFactorEnabled: boolean;
                } | null;
            } & {
                id: string;
                name: string;
                species: string;
                breed: string | null;
                dob: Date | null;
                microchipNumber: string | null;
                description: string | null;
                status: import("@prisma/client").$Enums.PetStatus;
                gender: import("@prisma/client").$Enums.PetGender | null;
                size: import("@prisma/client").$Enums.PetSize | null;
                weight: number | null;
                color: string | null;
                lostPhotos: string | null;
                isVaccinated: boolean;
                isSpayedNeutered: boolean;
                contactName: string | null;
                contactPhone: string | null;
                contactAddress: string | null;
                traits: string | null;
                idealHome: string | null;
                personalityTags: import("@prisma/client").Prisma.JsonValue | null;
                goodWith: import("@prisma/client").Prisma.JsonValue | null;
                badWith: import("@prisma/client").Prisma.JsonValue | null;
                vaccinationRecordUrls: import("@prisma/client").Prisma.JsonValue | null;
                vetVerificationStatus: import("@prisma/client").$Enums.VerificationStatus;
                qrCodeUrl: string | null;
                qrVerificationStatus: import("@prisma/client").$Enums.VerificationStatus;
                ownerId: string | null;
                createdAt: Date;
                updatedAt: Date;
                shelterId: string | null;
                lostLatitude: number | null;
                lostLongitude: number | null;
                lostRadius: number | null;
                lostDate: Date | null;
                lostContactName: string | null;
                lostContactPhone: string | null;
                lostContactAddress: string | null;
                lostLocation: string | null;
                lostDateTime: string | null;
                lostDetails: string | null;
                needsQrReplacement: boolean;
            }) | null;
        } & {
            id: string;
            status: import("@prisma/client").$Enums.TagStatus;
            petId: string | null;
        };
    } & {
        id: string;
        tagId: string;
        userId: string | null;
        scannedBy: string | null;
        phoneNumber: string | null;
        latitude: number | null;
        longitude: number | null;
        radius: number | null;
        message: string | null;
        images: import("@prisma/client").Prisma.JsonValue | null;
        status: import("@prisma/client").$Enums.TagReportStatus;
        scannedAt: Date;
    }>;
    resolveTagReport(reportId: string): Promise<{
        id: string;
        tagId: string;
        userId: string | null;
        scannedBy: string | null;
        phoneNumber: string | null;
        latitude: number | null;
        longitude: number | null;
        radius: number | null;
        message: string | null;
        images: import("@prisma/client").Prisma.JsonValue | null;
        status: import("@prisma/client").$Enums.TagReportStatus;
        scannedAt: Date;
    }>;
    getNearbyLostPets(lat: number, lng: number, radiusKm?: number): Promise<any>;
    scanTag(tagId: string): Promise<{
        id: string;
        name: string;
        breed: string;
        gender: string;
        color: string;
        dob: Date | null;
        status: string;
        image: string;
        owner: {
            name: string;
            phone: string;
            address: string;
            avatarUrl: string | null;
        } | null;
        note: string;
    }>;
}
