import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

export async function seedPetHotels() {
  const HOTELS_DATA = [
    // 1. NHẬT BẢN (Chuẩn 100% khớp ảnh thiết kế)
    {
      countryId: 'japan',
      name: "Doggy's Island",
      cityVi: 'Chiba, Nhật Bản',
      cityEn: 'Chiba, Japan',
      rating: 4.2,
      reviewsCount: 2619,
      imageUrl: 'src/database/prisma/mock-data/doggy-island.png',
      websiteUrl: 'https://doggys-island.jp/en/',
      sortOrder: 1,
    },
    {
      countryId: 'japan',
      name: 'Wan Wan Paradise',
      cityVi: 'Yamanashi, Nhật Bản',
      cityEn: 'Yamanashi, Japan',
      rating: 4.1,
      reviewsCount: 520,
      imageUrl: 'src/database/prisma/mock-data/wan-wan-paradise.png',
      websiteUrl: 'https://iconia.co.jp/en-us/hotel-wan-wan-paradise-yatsugatake-yamanashi',
      sortOrder: 2,
    },
    {
      countryId: 'japan',
      name: 'Wan Wan Paradise',
      cityVi: 'Shirahama, Nhật Bản',
      cityEn: 'Shirahama, Japan',
      rating: 4.4,
      reviewsCount: 152,
      imageUrl: 'src/database/prisma/mock-data/wan-wan-shirahama.png',
      websiteUrl: 'https://iconia.co.jp/en-us/hotel-wan-wan-paradise-premier-nanki-shirahama-wakayama',
      sortOrder: 3,
    },

    // 2. VIỆT NAM
    {
      countryId: 'vietnam',
      name: 'Four Seasons Resort',
      cityVi: 'Đà Nẵng, Việt Nam',
      cityEn: 'Da Nang, Vietnam',
      rating: 4.1,
      reviewsCount: 53,
      imageUrl: 'src/database/prisma/mock-data/four-seasons-resort.png',
      websiteUrl: 'https://www.fourseasons.com/hoian/',
      sortOrder: 3,
    },
    {
      countryId: 'vietnam',
      name: 'Wink Saigon Centre',
      cityVi: 'Hồ Chí Minh, Việt Nam',
      cityEn: 'Ho Chi Minh City, Vietnam',
      rating: 4.3,
      reviewsCount: 1300,
      imageUrl: 'src/database/prisma/mock-data/wink-saigon-centre.png',
      websiteUrl: 'https://wink-hotels.com/vi/hotel/wink-saigon-centre/',
      sortOrder: 4,
    },
    {
      countryId: 'vietnam',
      name: 'Hanoi La Palm Premier',
      cityVi: 'Hà Nội, Việt Nam',
      cityEn: 'Hanoi, Vietnam',
      rating: 4.7,
      reviewsCount: 284,
      imageUrl: 'src/database/prisma/mock-data/hanoi-la-palm-premier.png',
      websiteUrl: 'https://lapalmhotels.com/tour-services.html',
      sortOrder: 5,
    },

    // 3. TRUNG QUỐC
    {
      countryId: 'china',
      name: 'Kimpton Qiantan Shanghai',
      cityVi: 'Thượng Hải, Trung Quốc',
      cityEn: 'Shanghai, China',
      rating: 4.7,
      reviewsCount: 28,
      imageUrl: 'src/database/prisma/mock-data/kimpton-qiantan-shanghai.png',
      websiteUrl: 'https://kimptonshanghai.cn/',
      sortOrder: 3,
    },
    {
      countryId: 'china',
      name: 'Hyatt Regency Beijing Wangjing',
      cityVi: 'Bắc Kinh, Trung Quốc',
      cityEn: 'Beijing, China',
      rating: 4.4,
      reviewsCount: 102,
      imageUrl: 'src/database/prisma/mock-data/hyatt-regency-beijing-wangjing.png',
      websiteUrl: 'https://www.hyatt.com/hyatt-regency/en-US/nayrw-hyatt-regency-beijing-wangjing',
      sortOrder: 4,
    },
    {
      countryId: 'china',
      name: 'Canopy by Hilton Hangzhou Jinsha Lake',
      cityVi: 'Chiết Giang, Trung Quốc',
      cityEn: 'Zhejiang, China',
      rating: 4.6,
      reviewsCount: 11,
      imageUrl: 'src/database/prisma/mock-data/canopy-by-hilton-hangzhou-jinsha-lake.png',
      websiteUrl: 'https://www.hilton.com/en/hotels/hghpypy-canopy-hangzhou-jinsha-lake/',
      sortOrder: 5,
    },

    // 4. HÀN QUỐC
    {
      countryId: 'korea',
      name: "L'Escape Hotel",
      cityVi: 'Seoul, Hàn Quốc',
      cityEn: 'Seoul, South Korea',
      rating: 4.4,
      reviewsCount: 1649,
      imageUrl: 'src/database/prisma/mock-data/l-escape-hotel.png',
      websiteUrl: 'https://josunhotel.com/intro.do',
      sortOrder: 3,
    },
    {
      countryId: 'korea',
      name: 'The Point Hotel',
      cityVi: 'Busan, Hàn Quốc',
      cityEn: 'Busan, South Korea',
      rating: 4.2,
      reviewsCount: 156,
      imageUrl: 'src/database/prisma/mock-data/the-point-hotel.png',
      websiteUrl: 'https://pointhotel.com.au/',
      sortOrder: 4,
    },
    {
      countryId: 'korea',
      name: 'Jeju Western Grace Hotel',
      cityVi: 'Jeju, Hàn Quốc',
      cityEn: 'Jeju, South Korea',
      rating: 4.1,
      reviewsCount: 137,
      imageUrl: 'src/database/prisma/mock-data/jeju-western-grace-hotel.png',
      websiteUrl: 'https://www.seanhotelgroup.com/hotels/western_grace/en/',
      sortOrder: 5,
    },

    // 5. PHÁP
    {
      countryId: 'france',
      name: 'Le Negresco',
      cityVi: 'Nice, Pháp',
      cityEn: 'Nice, France',
      rating: 4.6,
      reviewsCount: 6670,
      imageUrl: 'src/database/prisma/mock-data/le-negresco.png',
      websiteUrl: 'https://www.lenegresco.com/en',
      sortOrder: 3,
    },
    {
      countryId: 'france',
      name: 'Four Seasons Hotel George V, Paris',
      cityVi: 'Paris, Pháp',
      cityEn: 'Paris, France',
      rating: 4.8,
      reviewsCount: 7360,
      imageUrl: 'src/database/prisma/mock-data/four-seasons-hotel-george-v-paris.png',
      websiteUrl: 'https://www.fourseasons.com/paris/?utm_source=google&utm_medium=paidsearch&utm_campaign=saa-par-hre-low-brd_brandhotel_georgev-na&utm_content=na-na&utm_term=na&gclsrc=aw.ds&gad_source=1&gad_campaignid=19807736850&gbraid=0AAAAAD9hWRsXNKdfTo6qUHjFlGpFyDmxy&gclid=CjwKCAjwwfnUBhAtEiwAfQpAYvChusSrQRFo2zT975-ZVvnJrMOnjP2VSyHkvzxMl7TSiDU29-0d-xoC2fgQAvD_BwE',
      sortOrder: 4,
    },
    {
      countryId: 'france',
      name: 'Hôtel Maison Mère',
      cityVi: 'Paris, Pháp',
      cityEn: 'Paris, France',
      rating: 4.7,
      reviewsCount: 766,
      imageUrl: 'src/database/prisma/mock-data/hotel-maison-mere.png',
      websiteUrl: 'https://www.maisonmere.co/',
      sortOrder: 5,
    },

    // 6. Ý
    {
      countryId: 'italy',
      name: 'Hotel de Russie',
      cityVi: 'Rome, Ý',
      cityEn: 'Rome, Italy',
      rating: 4.6,
      reviewsCount: 1906,
      imageUrl: 'src/database/prisma/mock-data/hotel-de-russie.png',
      websiteUrl: 'https://www.maisonmere.co/',
      sortOrder: 3,
    },
    {
      countryId: 'italy',
      name: 'Portrait Milano',
      cityVi: 'Milan, Ý',
      cityEn: 'Milan, Italy',
      rating: 4.6,
      reviewsCount: 863,
      imageUrl: 'src/database/prisma/mock-data/portrait-milano.png',
      websiteUrl: 'https://www.lungarnocollection.com/milan/portrait-milano/',
      sortOrder: 4,
    },
    {
      countryId: 'italy',
      name: 'Belmond Hotel Cipriani',
      cityVi: 'Venice, Ý',
      cityEn: 'Venice, Italy',
      rating: 4.7,
      reviewsCount: 681,
      imageUrl: 'src/database/prisma/mock-data/belmond-hotel-cipriani.png',
      websiteUrl: 'https://www.lungarnocollection.com/milan/portrait-milano/',
      sortOrder: 5,
    },

    // 7. ĐỨC
    {
      countryId: 'germany',
      name: 'The Ritz-Carlton',
      cityVi: 'Berlin, Đức',
      cityEn: 'Berlin, Germany',
      rating: 4.9,
      reviewsCount: 1239,
      imageUrl: 'src/database/prisma/mock-data/the-ritz-carlton.png',
      websiteUrl: 'https://www.lungarnocollection.com/milan/portrait-milano/',
      sortOrder: 3,
    },
    {
      countryId: 'germany',
      name: 'Platzl Hotel',
      cityVi: 'Munich, Đức',
      cityEn: 'Munich, Germany',
      rating: 4.5,
      reviewsCount: 1541,
      imageUrl: 'src/database/prisma/mock-data/platzl-hotel.png',
      websiteUrl: 'https://www.platzl.de/en/',
      sortOrder: 4,
    },
    {
      countryId: 'germany',
      name: 'Reichshof Hamburg',
      cityVi: 'Hamburg, Đức',
      cityEn: 'Hamburg, Germany',
      rating: 4.5,
      reviewsCount: 3981,
      imageUrl: 'src/database/prisma/mock-data/reichshof-hamburg.png',
      websiteUrl: 'https://www.reichshof-hotel-hamburg.de/',
      sortOrder: 5,
    },

    // 8. THỤY SỸ
    {
      countryId: 'switzerland',
      name: 'The Dolder Grand',
      cityVi: 'Zürich, Thụy Sỹ',
      cityEn: 'Zurich, Switzerland',
      rating: 4.7,
      reviewsCount: 4104,
      imageUrl: 'src/database/prisma/mock-data/the-dolder-grand.png',
      websiteUrl: 'https://www.thedoldergrand.com/',
      sortOrder: 3,
    },
    {
      countryId: 'switzerland',
      name: 'Hotel Schweizerhof Luzern',
      cityVi: 'Lucerne, Thụy Sỹ',
      cityEn: 'Lucerne, Switzerland',
      rating: 4.6,
      reviewsCount: 2804,
      imageUrl: 'src/database/prisma/mock-data/hotel-schweizerhof-luzern.png',
      websiteUrl: 'https://www.schweizerhof-luzern.ch/',
      sortOrder: 4,
    },
    {
      countryId: 'switzerland',
      name: 'Art Deco Hotel Montana',
      cityVi: 'Lucerne, Thụy Sỹ',
      cityEn: 'Lucerne, Switzerland',
      rating: 4.7,
      reviewsCount: 2307,
      imageUrl: 'src/database/prisma/mock-data/art-deco-hotel-montana.png',
      websiteUrl: 'https://www.hotel-montana.ch/en',
      sortOrder: 5,
    },

    // 9. HY LẠP
    {
      countryId: 'greece',
      name: 'The Margi',
      cityVi: 'Athens, Hy Lạp',
      cityEn: 'Athens, Greece',
      rating: 4.6,
      reviewsCount: 2206,
      imageUrl: 'src/database/prisma/mock-data/the-margi.png',
      websiteUrl: 'https://themargin.us/',
      sortOrder: 3,
    },
    {
      countryId: 'greece',
      name: 'Grand Hyatt Athens',
      cityVi: 'Athens, Hy Lạp',
      cityEn: 'Athens, Greece',
      rating: 4.3,
      reviewsCount: 7196,
      imageUrl: 'src/database/prisma/mock-data/grand-hyatt-athens.png',
      websiteUrl: 'https://www.hyatt.com/grand-hyatt/en-US/athgh-grand-hyatt-athens',
      sortOrder: 4,
    },
    {
      countryId: 'greece',
      name: 'Hotel Grande Bretagne',
      cityVi: 'Athens, Hy Lạp',
      cityEn: 'Athens, Greece',
      rating: 4.8,
      reviewsCount: 6767,
      imageUrl: 'src/database/prisma/mock-data/hotel-grande-bretagne.png',
      websiteUrl: 'https://www.marriott.com/en-us/hotels/athlc-hotel-grande-bretagne-a-luxury-collection-hotel-athens/overview/',
      sortOrder: 5,
    },

    // 10. AI CẬP
    {
      countryId: 'egypt',
      name: 'The Nile Ritz-Carlton',
      cityVi: 'Cairo, Ai Cập',
      cityEn: 'Cairo, Egypt',
      rating: 4.7,
      reviewsCount: 19447,
      imageUrl: 'src/database/prisma/mock-data/the-nile-ritz-carlton.png',
      websiteUrl: 'https://www.marriott.com/en-us/hotels/athlc-hotel-grande-bretagne-a-luxury-collection-hotel-athens/overview/',
      sortOrder: 3,
    },
    {
      countryId: 'egypt',
      name: 'Fairmont Nile City',
      cityVi: 'Cairo, Ai Cập',
      cityEn: 'Cairo, Egypt',
      rating: 4.7,
      reviewsCount: 25984,
      imageUrl: 'src/database/prisma/mock-data/fairmont-nile-city.png',
      websiteUrl: 'https://www.fairmont.com/en.html',
      sortOrder: 4,
    },
    {
      countryId: 'egypt',
      name: 'Hilton Cairo Zamalek Residences',
      cityVi: 'Cairo, Ai Cập',
      cityEn: 'Cairo, Egypt',
      rating: 4.4,
      reviewsCount: 4937,
      imageUrl: 'src/database/prisma/mock-data/hilton-cairo-zamalek-residences.png',
      websiteUrl: 'https://www.hilton.com/en/hotels/caizrhi-hilton-cairo-zamalek-residences/',
      sortOrder: 5,
    },
  ];

  console.log('Seeding 12 countries Pet Hotels...');
  for (const hotel of HOTELS_DATA) {
    await prisma.petHotel.create({
      data: hotel,
    });
  }
  console.log('Done seeding Pet Hotels!');
}

seedPetHotels()
  .catch((e) => {
    console.error('LỖI KHI SEED:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });