import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

export async function seedPetHotels() {
  const HOTELS_DATA = [
    // 1. NHẬT BẢN (Chuẩn 100% khớp ảnh thiết kế)
    {
      countryId: 'japan',
      name: "Doggy's Island",
      cityVi: 'Chiba, Nhật Bản',
      cityEn: 'Chiba, Japan',
      rating: 4.2,
      reviewsCount: 2619,
      imageUrl: '/mock-data/doggy-island.png',
      websiteUrl: 'https://doggys-island.jp/',
      sortOrder: 1,
    },
    {
      countryId: 'japan',
      name: 'Wan Wan Paradise',
      cityVi: 'Yamanashi, Nhật Bản',
      cityEn: 'Yamanashi, Japan',
      rating: 4.1,
      reviewsCount: 520,
      imageUrl: '/mock-data/wan-wan-paradise.png',
      websiteUrl: 'https://www.izumigo.co.jp/hotel/wanwan/',
      sortOrder: 2,
    },
    {
      countryId: 'japan',
      name: 'Wan Wan Paradise',
      cityVi: 'Shirahama, Nhật Bản',
      cityEn: 'Shirahama, Japan',
      rating: 4.4,
      reviewsCount: 152,
      imageUrl: '/mock-data/wan-wan-shirahama.png',
      websiteUrl: 'https://www.izumigo.co.jp/hotel/wanwan/shirahama/',
      sortOrder: 3,
    },

    // 2. VIỆT NAM
    {
      countryId: 'vietnam',
      name: 'Thao Dien Pet Resort & Spa',
      cityVi: 'TP. Hồ Chí Minh, Việt Nam',
      cityEn: 'Ho Chi Minh City, Vietnam',
      rating: 4.8,
      reviewsCount: 489,
      imageUrl: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?q=80&w=600&auto=format&fit=crop',
      websiteUrl: 'https://petresort.vn',
      sortOrder: 1,
    },
    {
      countryId: 'vietnam',
      name: 'Da Nang Ocean Paws Villa',
      cityVi: 'Đà Nẵng, Việt Nam',
      cityEn: 'Da Nang, Vietnam',
      rating: 4.6,
      reviewsCount: 215,
      imageUrl: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?q=80&w=600&auto=format&fit=crop',
      websiteUrl: 'https://danangpetvilla.com',
      sortOrder: 2,
    },
    {
      countryId: 'vietnam',
      name: 'Four Seasons Resort',
      cityVi: 'Đà Nẵng, Việt Nam',
      cityEn: 'Da Nang, Vietnam',
      rating: 4.1,
      reviewsCount: 53,
      imageUrl: '/mock-data/four-seasons-resort.png',
      websiteUrl: 'https://www.fourseasons.com/danang/',
      sortOrder: 3,
    },
    {
      countryId: 'vietnam',
      name: 'Wink Saigon Centre',
      cityVi: 'Hồ Chí Minh, Việt Nam',
      cityEn: 'Ho Chi Minh City, Vietnam',
      rating: 4.3,
      reviewsCount: 1300,
      imageUrl: '/mock-data/wink-saigon-centre.png',
      websiteUrl: 'https://www.winkhotels.com/saigon-centre',
      sortOrder: 4,
    },
    {
      countryId: 'vietnam',
      name: 'Hanoi La Palm Premier',
      cityVi: 'Hà Nội, Việt Nam',
      cityEn: 'Hanoi, Vietnam',
      rating: 4.7,
      reviewsCount: 284,
      imageUrl: '/mock-data/hanoi-la-palm-premier.png',
      websiteUrl: '',
      sortOrder: 5,
    },

    // 3. TRUNG QUỐC
    {
      countryId: 'china',
      name: 'Chong’ai Luxury Pet Palace',
      cityVi: 'Thượng Hải, Trung Quốc',
      cityEn: 'Shanghai, China',
      rating: 4.5,
      reviewsCount: 830,
      imageUrl: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?q=80&w=600&auto=format&fit=crop',
      websiteUrl: 'https://petpalace.cn',
      sortOrder: 1,
    },
    {
      countryId: 'china',
      name: 'Beijing Paws Boutique Inn',
      cityVi: 'Bắc Kinh, Trung Quốc',
      cityEn: 'Beijing, China',
      rating: 4.3,
      reviewsCount: 410,
      imageUrl: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?q=80&w=600&auto=format&fit=crop',
      websiteUrl: 'https://beijingpaws.com',
      sortOrder: 2,
    },
    {
      countryId: 'china',
      name: 'Kimpton Qiantan Shanghai',
      cityVi: 'Thượng Hải, Trung Quốc',
      cityEn: 'Shanghai, China',
      rating: 4.7,
      reviewsCount: 28,
      imageUrl: '/mock-data/kimpton-qiantan-shanghai.png',
      websiteUrl: 'https://www.ihg.com/kimptonhotels/hotels/us/en/shanghai/skqth/hoteldetail',
      sortOrder: 3,
    },
    {
      countryId: 'china',
      name: 'Hyatt Regency Beijing Wangjing',
      cityVi: 'Bắc Kinh, Trung Quốc',
      cityEn: 'Beijing, China',
      rating: 4.4,
      reviewsCount: 102,
      imageUrl: '/mock-data/hyatt-regency-beijing-wangjing.png',
      websiteUrl: 'https://www.hyatt.com/hyatt-regency/en-US/bjshr-hyatt-regency-beijing-wangjing',
      sortOrder: 4,
    },
    {
      countryId: 'china',
      name: 'Canopy by Hilton Hangzhou Jinsha Lake',
      cityVi: 'Chiết Giang, Trung Quốc',
      cityEn: 'Zhejiang, China',
      rating: 4.6,
      reviewsCount: 11,
      imageUrl: '/mock-data/canopy-by-hilton-hangzhou-jinsha-lake.png',
      websiteUrl: 'https://www.hilton.com/en/hotels/hgzclcy-canopy-hangzhou-jinsha-lake/',
      sortOrder: 5,
    },

    // 4. HÀN QUỐC
    {
      countryId: 'korea',
      name: 'Gold Pet Resort',
      cityVi: 'Yongin, Hàn Quốc',
      cityEn: 'Yongin, South Korea',
      rating: 4.7,
      reviewsCount: 1420,
      imageUrl: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?q=80&w=600&auto=format&fit=crop',
      websiteUrl: 'https://goldpetresort.com',
      sortOrder: 1,
    },
    {
      countryId: 'korea',
      name: 'Sono Pet Club & Resorts Vivaldi',
      cityVi: 'Gangwon, Hàn Quốc',
      cityEn: 'Gangwon, South Korea',
      rating: 4.8,
      reviewsCount: 3100,
      imageUrl: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?q=80&w=600&auto=format&fit=crop',
      websiteUrl: 'https://sonohotelsresorts.com',
      sortOrder: 2,
    },
    {
      countryId: 'korea',
      name: "L'Escape Hotel",
      cityVi: 'Seoul, Hàn Quốc',
      cityEn: 'Seoul, South Korea',
      rating: 4.4,
      reviewsCount: 1649,
      imageUrl: '/mock-data/l-escape-hotel.png',
      websiteUrl: 'https://www.lescapehotel.com',
      sortOrder: 3,
    },
    {
      countryId: 'korea',
      name: 'The Point Hotel',
      cityVi: 'Busan, Hàn Quốc',
      cityEn: 'Busan, South Korea',
      rating: 4.2,
      reviewsCount: 156,
      imageUrl: '/mock-data/the-point-hotel.png',
      websiteUrl: '',
      sortOrder: 4,
    },
    {
      countryId: 'korea',
      name: 'Jeju Western Grace Hotel',
      cityVi: 'Jeju, Hàn Quốc',
      cityEn: 'Jeju, South Korea',
      rating: 4.1,
      reviewsCount: 137,
      imageUrl: '/mock-data/jeju-western-grace-hotel.png',
      websiteUrl: '',
      sortOrder: 5,
    },

    // 5. PHÁP
    {
      countryId: 'france',
      name: 'Aristide Hôtel pour Chats & Chiens',
      cityVi: 'Paris, Pháp',
      cityEn: 'Paris, France',
      rating: 4.9,
      reviewsCount: 940,
      imageUrl: 'https://images.unsplash.com/photo-1584132967334-10e028bd69f7?q=80&w=600&auto=format&fit=crop',
      websiteUrl: 'https://aristide-hotel.com',
      sortOrder: 1,
    },
    {
      countryId: 'france',
      name: 'Le Dog Hôtel de la Côte d’Azur',
      cityVi: 'Nice, Pháp',
      cityEn: 'Nice, France',
      rating: 4.6,
      reviewsCount: 380,
      imageUrl: 'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?q=80&w=600&auto=format&fit=crop',
      websiteUrl: 'https://ledoghotel.fr',
      sortOrder: 2,
    },
    {
      countryId: 'france',
      name: 'Le Negresco',
      cityVi: 'Nice, Pháp',
      cityEn: 'Nice, France',
      rating: 4.6,
      reviewsCount: 6670,
      imageUrl: '/mock-data/le-negresco.png',
      websiteUrl: 'https://www.hotel-negresco-nice.com',
      sortOrder: 3,
    },
    {
      countryId: 'france',
      name: 'Four Seasons Hotel George V, Paris',
      cityVi: 'Paris, Pháp',
      cityEn: 'Paris, France',
      rating: 4.8,
      reviewsCount: 7360,
      imageUrl: '/mock-data/four-seasons-hotel-george-v-paris.png',
      websiteUrl: 'https://www.fourseasons.com/paris/',
      sortOrder: 4,
    },
    {
      countryId: 'france',
      name: 'Hôtel Maison Mère',
      cityVi: 'Paris, Pháp',
      cityEn: 'Paris, France',
      rating: 4.7,
      reviewsCount: 766,
      imageUrl: '/mock-data/hotel-maison-mere.png',
      websiteUrl: 'https://www.maisonmereparis.com',
      sortOrder: 5,
    },

    // 6. Ý
    {
      countryId: 'italy',
      name: 'Bau Bau Village Resort',
      cityVi: 'Savona, Ý',
      cityEn: 'Savona, Italy',
      rating: 4.7,
      reviewsCount: 1205,
      imageUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=600&auto=format&fit=crop',
      websiteUrl: 'https://baubauvillage.it',
      sortOrder: 1,
    },
    {
      countryId: 'italy',
      name: 'Tuscany Paws Country Lodge',
      cityVi: 'Tuscany, Ý',
      cityEn: 'Tuscany, Italy',
      rating: 4.8,
      reviewsCount: 560,
      imageUrl: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?q=80&w=600&auto=format&fit=crop',
      websiteUrl: 'https://tuscanydoglodge.com',
      sortOrder: 2,
    },
    {
      countryId: 'italy',
      name: 'Hotel de Russie',
      cityVi: 'Rome, Ý',
      cityEn: 'Rome, Italy',
      rating: 4.6,
      reviewsCount: 1906,
      imageUrl: '/mock-data/hotel-de-russie.png',
      websiteUrl: 'https://www.roccofortehotels.com/hotels-and-resorts/hotel-de-russie/',
      sortOrder: 3,
    },
    {
      countryId: 'italy',
      name: 'Portrait Milano',
      cityVi: 'Milan, Ý',
      cityEn: 'Milan, Italy',
      rating: 4.6,
      reviewsCount: 863,
      imageUrl: '/mock-data/portrait-milano.png',
      websiteUrl: 'https://www.lungarnocollection.com/portrait-milano/',
      sortOrder: 4,
    },
    {
      countryId: 'italy',
      name: 'Belmond Hotel Cipriani',
      cityVi: 'Venice, Ý',
      cityEn: 'Venice, Italy',
      rating: 4.7,
      reviewsCount: 681,
      imageUrl: '/mock-data/belmond-hotel-cipriani.png',
      websiteUrl: 'https://www.belmond.com/hotels/europe/italy/venice/belmond-hotel-cipriani/',
      sortOrder: 5,
    },

    // 7. ĐỨC
    {
      countryId: 'germany',
      name: 'Hundehof Bavarian Luxury Inn',
      cityVi: 'Munich, Đức',
      cityEn: 'Munich, Germany',
      rating: 4.7,
      reviewsCount: 680,
      imageUrl: 'https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?q=80&w=600&auto=format&fit=crop',
      websiteUrl: 'https://hundehof-bayern.de',
      sortOrder: 1,
    },
    {
      countryId: 'germany',
      name: 'Canis Resort Berlin',
      cityVi: 'Berlin, Đức',
      cityEn: 'Berlin, Germany',
      rating: 4.6,
      reviewsCount: 412,
      imageUrl: 'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?q=80&w=600&auto=format&fit=crop',
      websiteUrl: 'https://canisresort.com',
      sortOrder: 2,
    },
    {
      countryId: 'germany',
      name: 'The Ritz-Carlton',
      cityVi: 'Berlin, Đức',
      cityEn: 'Berlin, Germany',
      rating: 4.9,
      reviewsCount: 1239,
      imageUrl: '/mock-data/the-ritz-carlton.png',
      websiteUrl: 'https://www.ritzcarlton.com/en/hotels/germany/berlin',
      sortOrder: 3,
    },
    {
      countryId: 'germany',
      name: 'Platzl Hotel',
      cityVi: 'Munich, Đức',
      cityEn: 'Munich, Germany',
      rating: 4.5,
      reviewsCount: 1541,
      imageUrl: '/mock-data/platzl-hotel.png',
      websiteUrl: 'https://www.platzl.de',
      sortOrder: 4,
    },
    {
      countryId: 'germany',
      name: 'Reichshof Hamburg',
      cityVi: 'Hamburg, Đức',
      cityEn: 'Hamburg, Germany',
      rating: 4.5,
      reviewsCount: 3981,
      imageUrl: '/mock-data/reichshof-hamburg.png',
      websiteUrl: 'https://www.reichshof-hotel-hamburg.com',
      sortOrder: 5,
    },

    // 8. THỤY SỸ
    {
      countryId: 'switzerland',
      name: 'Alpine Paws Grand Hotel',
      cityVi: 'Zermatt, Thụy Sỹ',
      cityEn: 'Zermatt, Switzerland',
      rating: 4.9,
      reviewsCount: 890,
      imageUrl: 'https://images.unsplash.com/photo-1502784444187-359ac186c5bb?q=80&w=600&auto=format&fit=crop',
      websiteUrl: 'https://alpinepawshotel.ch',
      sortOrder: 1,
    },
    {
      countryId: 'switzerland',
      name: 'Geneva Lake Pet Haven',
      cityVi: 'Geneva, Thụy Sỹ',
      cityEn: 'Geneva, Switzerland',
      rating: 4.7,
      reviewsCount: 340,
      imageUrl: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?q=80&w=600&auto=format&fit=crop',
      websiteUrl: 'https://genevapethaven.ch',
      sortOrder: 2,
    },
    {
      countryId: 'switzerland',
      name: 'The Dolder Grand',
      cityVi: 'Zürich, Thụy Sỹ',
      cityEn: 'Zurich, Switzerland',
      rating: 4.7,
      reviewsCount: 4104,
      imageUrl: '/mock-data/the-dolder-grand.png',
      websiteUrl: 'https://www.thedoldergrand.com',
      sortOrder: 3,
    },
    {
      countryId: 'switzerland',
      name: 'Hotel Schweizerhof Luzern',
      cityVi: 'Lucerne, Thụy Sỹ',
      cityEn: 'Lucerne, Switzerland',
      rating: 4.6,
      reviewsCount: 2804,
      imageUrl: '/mock-data/hotel-schweizerhof-luzern.png',
      websiteUrl: 'https://www.schweizerhof-luzern.ch',
      sortOrder: 4,
    },
    {
      countryId: 'switzerland',
      name: 'Art Deco Hotel Montana',
      cityVi: 'Lucerne, Thụy Sỹ',
      cityEn: 'Lucerne, Switzerland',
      rating: 4.7,
      reviewsCount: 2307,
      imageUrl: '/mock-data/art-deco-hotel-montana.png',
      websiteUrl: 'https://www.hotel-montana.ch',
      sortOrder: 5,
    },

    // 9. HY LẠP
    {
      countryId: 'greece',
      name: 'Mykonos Pet Palace Suites',
      cityVi: 'Mykonos, Hy Lạp',
      cityEn: 'Mykonos, Greece',
      rating: 4.6,
      reviewsCount: 310,
      imageUrl: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?q=80&w=600&auto=format&fit=crop',
      websiteUrl: 'https://mykonospetpalace.gr',
      sortOrder: 1,
    },
    {
      countryId: 'greece',
      name: 'Athens Dog & Cat Luxury Villa',
      cityVi: 'Athens, Hy Lạp',
      cityEn: 'Athens, Greece',
      rating: 4.5,
      reviewsCount: 480,
      imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=600&auto=format&fit=crop',
      websiteUrl: 'https://athenspetresort.com',
      sortOrder: 2,
    },
    {
      countryId: 'greece',
      name: 'The Margi',
      cityVi: 'Athens, Hy Lạp',
      cityEn: 'Athens, Greece',
      rating: 4.6,
      reviewsCount: 2206,
      imageUrl: '/mock-data/the-margi.png',
      websiteUrl: 'https://www.themargi.gr',
      sortOrder: 3,
    },
    {
      countryId: 'greece',
      name: 'Grand Hyatt Athens',
      cityVi: 'Athens, Hy Lạp',
      cityEn: 'Athens, Greece',
      rating: 4.3,
      reviewsCount: 7196,
      imageUrl: '/mock-data/grand-hyatt-athens.png',
      websiteUrl: 'https://www.hyatt.com/grand-hyatt/en-US/athgh-grand-hyatt-athens',
      sortOrder: 4,
    },
    {
      countryId: 'greece',
      name: 'Hotel Grande Bretagne',
      cityVi: 'Athens, Hy Lạp',
      cityEn: 'Athens, Greece',
      rating: 4.8,
      reviewsCount: 6767,
      imageUrl: '/mock-data/hotel-grande-bretagne.png',
      websiteUrl: 'https://www.marriott.com/en-us/hotels/atheg-hotel-grande-bretagne-a-luxury-collection-hotel-athens/',
      sortOrder: 5,
    },

    // 10. AI CẬP
    {
      countryId: 'egypt',
      name: 'Nile Pet Oasis Resort',
      cityVi: 'Cairo, Ai Cập',
      cityEn: 'Cairo, Egypt',
      rating: 4.3,
      reviewsCount: 290,
      imageUrl: 'https://images.unsplash.com/photo-1571770095004-6b61b1cf308a?q=80&w=600&auto=format&fit=crop',
      websiteUrl: 'https://nilepetoasis.com',
      sortOrder: 1,
    },
    {
      countryId: 'egypt',
      name: 'Red Sea Canine Haven',
      cityVi: 'Hurghada, Ai Cập',
      cityEn: 'Hurghada, Egypt',
      rating: 4.4,
      reviewsCount: 180,
      imageUrl: 'https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=600&auto=format&fit=crop',
      websiteUrl: 'https://redseapaws.com',
      sortOrder: 2,
    },
    {
      countryId: 'egypt',
      name: 'The Nile Ritz-Carlton',
      cityVi: 'Cairo, Ai Cập',
      cityEn: 'Cairo, Egypt',
      rating: 4.7,
      reviewsCount: 19447,
      imageUrl: '/mock-data/the-nile-ritz-carlton.png',
      websiteUrl: 'https://www.ritzcarlton.com/en/hotels/egypt/cairo',
      sortOrder: 3,
    },
    {
      countryId: 'egypt',
      name: 'Fairmont Nile City',
      cityVi: 'Cairo, Ai Cập',
      cityEn: 'Cairo, Egypt',
      rating: 4.7,
      reviewsCount: 25984,
      imageUrl: '/mock-data/fairmont-nile-city.png',
      websiteUrl: 'https://www.fairmont.com/nile-city-cairo/',
      sortOrder: 4,
    },
    {
      countryId: 'egypt',
      name: 'Hilton Cairo Zamalek Residences',
      cityVi: 'Cairo, Ai Cập',
      cityEn: 'Cairo, Egypt',
      rating: 4.4,
      reviewsCount: 4937,
      imageUrl: '/mock-data/hilton-cairo-zamalek-residences.png',
      websiteUrl: 'https://www.hilton.com/en/hotels/caizarw-hilton-cairo-zamalek-residences/',
      sortOrder: 5,
    },

    // 11. HOA KỲ (USA)
    {
      countryId: 'usa',
      name: 'The Barkley Pet Hotel & Spa',
      cityVi: 'Los Angeles, Hoa Kỳ',
      cityEn: 'Los Angeles, USA',
      rating: 4.8,
      reviewsCount: 3840,
      imageUrl: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?q=80&w=600&auto=format&fit=crop',
      websiteUrl: 'https://thebarkleypethotel.com',
      sortOrder: 1,
    },
    {
      countryId: 'usa',
      name: 'D Pet Hotels New York',
      cityVi: 'New York, Hoa Kỳ',
      cityEn: 'New York, USA',
      rating: 4.7,
      reviewsCount: 2190,
      imageUrl: 'https://images.unsplash.com/photo-1566665797739-1674de7a421a?q=80&w=600&auto=format&fit=crop',
      websiteUrl: 'https://dpethotels.com',
      sortOrder: 2,
    },

    // 12. VƯƠNG QUỐC ANH (UK)
    {
      countryId: 'uk',
      name: 'The Pet Spa at Harrods & Country Club',
      cityVi: 'London, Vương quốc Anh',
      cityEn: 'London, United Kingdom',
      rating: 4.9,
      reviewsCount: 1650,
      imageUrl: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?q=80&w=600&auto=format&fit=crop',
      websiteUrl: 'https://thepetspa.co.uk',
      sortOrder: 1,
    },
    {
      countryId: 'uk',
      name: 'Cotswolds Canine Estate',
      cityVi: 'Gloucestershire, Vương quốc Anh',
      cityEn: 'Gloucestershire, United Kingdom',
      rating: 4.8,
      reviewsCount: 870,
      imageUrl: 'https://images.unsplash.com/photo-1505691938895-1758d7feb511?q=80&w=600&auto=format&fit=crop',
      websiteUrl: 'https://cotswoldscanine.co.uk',
      sortOrder: 2,
    },
  ];

  console.log('Seeding 12 countries Pet Hotels...');
  for (const hotel of HOTELS_DATA) {
    await prisma.petHotel.create({
      data: hotel,
    });
  }
  console.log('Done seeding Pet Hotels!');
}